# custom config settings
# replace these in the config of your custom project or by overriding these variables
damap:
  origins: https://your.frontend.com,https://*.yourdomain.com
  auth:
    url: https://your.authentication.server
    client:
      backend: your-backend-authentication-client-id
      frontend: your-frontend-authentication-client-id
    scope: your-authentication-scope
    user: your-authentication-claim-holding-the-user-id
  datasource:
    url: jdbc:your-datasource-language:your-datasource.address
    username: your-datasource-username
    password: your-datasource-password
  projects-url: http://your.project.management.system.com
  persons-url: http://your.personnel.management.system.com
  fits-url: http://your.fits.service:1234

# general config settings
quarkus:
  http:
    cors:
      ~: true
      origins: ${damap.origins}
      headers: origin,content-type,accept,authorization
      access-control-max-age: 1

  oidc: 
    auth-server-url: ${damap.auth.url}
    client-id: ${damap.auth.client.backend}

  datasource:
    jdbc:
      url: ${damap.datasource.url}
    db-kind: postgresql
    username: ${damap.datasource.username}
    password: ${damap.datasource.password}

  hibernate-orm:
    database:
      generation: none
    sql-load-script: no-file

  cache:
    caffeine:
      "repositories":
        expire-after-write: P1D
      "repository":
        expire-after-write: P1D

  liquibase:
    migrate-at-start: true
    change-log: db/changeLog.yaml

rest:
  projects/mp-rest/url: ${damap.projects-url}
  persons/mp-rest/url: ${damap.persons-url}
  fits/mp-rest/url: ${damap.fits-url}
  r3data:
    repositories/mp-rest/url: https://www.re3data.org/api
    repositories/mp-rest/scope: javax.inject.Singleton

"%dev":
  damap:
    origins: http://localhost:4200
    datasource:
      url: jdbc:postgresql://localhost:5432/damap
      username: damap
      password: pw4damap

"%test":
