pipelines:
  openshift:
    stages:
      deploy:
        enabled: false
  maven:
    imageTag: jdk-11
    stages:
      publish:
        enabled: false

whenBranch:
  next:
    pipelines:
      maven:
        stages:
          publish:
            enabled: true
    post:
      success:
        trigger: [ "CSD/damap-tuw-be/next" ]
  master:
    pipelines:
      maven:
        stages:
          publish:
            enabled: true
