pipelines:
  openshift:
    stages:
      deploy:
        enabled: false
  maven:
    stages:
      publish:
        enabled: false

whenBranch:
  "next":
    pipelines:
      maven:
        stages:
          publish:
            enabled: true
    post:
      success:
        trigger: [ "CSD/job/damap-tuw-be/job/next" ]