name: Run Sonar analysis

on:
  workflow_run:
    workflows: [test]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
      - name: Run Sonar analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          mvn -Psonar
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=tuwien-csd
          -Dsonar.projectKey=tuwien-csd_damap-backend
          -Dsonar.sourceEncoding=UTF-8
          -Dsonar.coverage.exclusions=docker/**/*,
          sonar:sonar